name: mcq_trainer
description: A Multiple Choice Question Trainer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  drift: ^2.16.0
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.18
  ffi: ^2.1.2
  
  # Files & Path
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # Logic & UI
  provider: ^6.1.2
  csv: ^6.0.0
  shared_preferences: ^2.2.3
  
  file_picker: ^8.0.3
  share_plus: ^9.0.0 
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
  assets:
    - assets/questions.csv
    - assets/images/